package com.lazai.exception;

import com.lazai.utils.TraceIdUtil;
import graphql.GraphQLError;
import graphql.GraphqlErrorBuilder;
import graphql.schema.DataFetchingEnvironment;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.slf4j.MDC;
import org.springframework.graphql.execution.DataFetcherExceptionResolverAdapter;
import org.springframework.graphql.execution.ErrorType;
import org.springframework.stereotype.Component;

@Component
public class GraphQLExceptionResolver extends DataFetcherExceptionResolverAdapter {

    private static final Logger ERROR_LOGGER = LoggerFactory.getLogger("ERROR_LOG");

    @Override
    protected GraphQLError resolveToSingleError(Throwable ex, DataFetchingEnvironment env) {
        String traceId = MDC.get(TraceIdUtil.TRACE_ID);
        if (ex instanceof DomainException) {
            ERROR_LOGGER.error("GraphQL handle exception:",ex);
            ErrorType errorType = ErrorType.INTERNAL_ERROR;
            if(((DomainException) ex).getCode() == 401){
                errorType = ErrorType.UNAUTHORIZED;
            }
            return GraphqlErrorBuilder.newError()
                    .errorType(errorType)
                    .message("traceId: "+traceId + " " + ex.getMessage())
                    .path(env.getExecutionStepInfo().getPath())
                    .location(env.getField().getSourceLocation())
                    .build();
        } else {
            ERROR_LOGGER.error("GraphQL not handle exception:",ex);
            return GraphqlErrorBuilder.newError()
                    .errorType(ErrorType.BAD_REQUEST)
                    .message("traceId: "+ traceId + " " + ex.getMessage())
                    .path(env.getExecutionStepInfo().getPath())
                    .location(env.getField().getSourceLocation())
                    .build();
        }
    }
}